#!/bin/python3

import os
import sys

#
# Complete the gradingStudents function below.
#
def gradingStudents(grades):
    #
    # Write your code here.
    #
    
    newGrades=[]
    for i in range(len(grades)):
            x=grades[i]
            d=divmod(x,5)
            newX=x
            if(x>=38):
                if(d[1]>=3):
                 newX=(d[0]+1)*5
           
            newGrades.append(newX)
    return(newGrades)

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    grades = []

    for _ in range(n):
        grades_item = int(input())
        grades.append(grades_item)

    result = gradingStudents(grades)

    f.write('\n'.join(map(str, result)))
    f.write('\n')

    f.close()
